[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[type.rust.extend-identifiers]
arange = "arange"
EmbedNd = "EmbedNd"
from_mmaped_safetensors = "from_mmaped_safetensors"
nin_shortcut = "nin_shortcut"
